remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins

title: Lab Lino
description: A simple blog about Cybersecurity, Quantum Computing an Artificial Intelligence
author: Jullyano Lino
email: contato@jullyanolino.com
url: https://jullyanolino.com
theme: jekyll-theme-midnight
